package com.example.demo.Seguridad.Enum;

public enum Permit {
    // --- USUARIO CONTROLLER ---
    USUARIO_VER,
    USUARIO_MODIFICAR,
    USUARIO_REACTIVAR,
    USUARIO_DESACTIVAR,
    USUARIO_LIKE,
    USUARIO_QUITAR_LIKE,
    USUARIO_VER_LIKES,
    USUARIO_LISTAR_ACTIVOS,
    USUARIO_LISTAR_DESACTIVADOS,

    // --- LISTAS CONTROLLER ---
    LISTA_CREAR,
    LISTA_AGREGAR_CONTENIDO,
    LISTA_VER_TODAS,
    LISTA_VER_DETALLE,
    LISTA_CAMBIAR_NOMBRE,
    LISTA_CAMBIAR_ESTADO,
    LISTA_ELIMINAR_CONTENIDO,
    LISTA_ELIMINAR,
    LISTA_VER_PUBLICAS,

    // --- SUSCRIPCION CONTROLLER ---
    SUSCRIPCION_CREAR,
    SUSCRIPCION_RENOVAR,
    SUSCRIPCION_VER_TODAS,
    SUSCRIPCION_VER_ACTIVAS,
    SUSCRIPCION_VER_POR_ID,

    // --- PLAN CONTROLLER ---
    PLAN_VER,
    PLAN_EDITAR,

    // --- PAGO CONTROLLER ---
    PAGO_VER_TODOS,
    PAGO_VER_POR_SUSCRIPCION,
    PAGO_VER_POR_ID,

    // --- OFERTA CONTROLLER ---
    OFERTA_CREAR,
    OFERTA_RENOVAR,
    OFERTA_VER_TODAS,
    OFERTA_VER_ACTIVAS,

    // --- CONTENIDO CONTROLLER ---
    VER_CONTENIDO_ACTIVO,
    VER_CONTENIDO_BAJA,
    ACTIVAR_CONTENIDO,
    DESACTIVAR_CONTENIDO,

    // --- PELICULA CONTROLLER ---
    VER_PELICULAS,

    // --- SERIE CONTROLLER ---
    SERIES_READ,
    SERIES_WRITE,

    // --- RESENIA CONTROLLER ---
    CREAR_RESENIA,
    ELIMINAR_RESENIA,
    ELIMINAR_RESENIA_POR_USUARIO_Y_CONTENIDO,
    VER_RESENIAS_POR_USUARIO,
    MODIFICAR_RESENIA
}
