package com.example.demo.Seguridad.Enum;

public enum Permit {
    // --- USUARIO CONTROLLER ---
    USUARIO_VER,
    USUARIO_CREAR_ADMIN,
    USUARIO_MODIFICAR,
    USUARIO_REACTIVAR,
    USUARIO_DESACTIVAR,
    USUARIO_LIKE,
    USUARIO_QUITAR_LIKE,
    USUARIO_VER_LIKES,
    USUARIO_LISTAR_ACTIVOS,
    USUARIO_LISTAR_DESACTIVADOS,
    USUARIO_SOLICITAR_SOPORTE,
    USUARIO_ENVIAR_ANUNCIO,

    // --- LISTAS CONTROLLER ---
    LISTA_CREAR,
    LISTA_AGREGAR_CONTENIDO,
    LISTA_VER_TODAS,
    LISTA_VER_DETALLE,
    LISTA_CAMBIAR_NOMBRE,
    LISTA_CAMBIAR_ESTADO,
    LISTA_ELIMINAR_CONTENIDO,
    LISTA_ELIMINAR,
    LISTA_VER_PUBLICAS,
    LISTA_VER_PROPIAS,

    // --- SUSCRIPCION CONTROLLER ---
    SUSCRIPCION_CREAR,
    SUSCRIPCION_RENOVAR,
    SUSCRIPCION_CAMBIAR_PLAN,
    SUSCRIPCION_VER_TODAS,
    SUSCRIPCION_VER_ACTIVAS,
    SUSCRIPCION_VER_POR_ID,

    // --- PLAN CONTROLLER ---
    PLAN_VER,
    PLAN_EDITAR,

    // --- PAGO CONTROLLER ---
    PAGO_VER_TODOS,
    PAGO_VER_POR_SUSCRIPCION,
    PAGO_VER_POR_ID,

    // --- OFERTA CONTROLLER ---
    OFERTA_CREAR,
    OFERTA_RENOVAR,
    OFERTA_VER_TODAS,
    OFERTA_VER_ACTIVAS,

    // --- CONTENIDO CONTROLLER ---
    VER_CONTENIDO_ACTIVO,
    VER_CONTENIDO_BAJA,
    ACTIVAR_CONTENIDO,
    DESACTIVAR_CONTENIDO,
    BUSCAR_NUEVO_CONTENIDO_POR_NOMBRE,
    VISUALIZAR_RECOMENDACIONES_POR_LIKES,

    // --- PELICULA CONTROLLER ---
    VER_PELICULAS,

    // --- SERIE CONTROLLER ---
    SERIES_READ,
    SERIES_WRITE,

    // --- GRUPO CONTROLLER ---
    CREAR_GRUPO,
    VER_GRUPO,
    MODIFICAR_GRUPO,
    AGREGAR_USUARIO_A_GRUPO,
    ELIMINAR_USUARIO_DE_GRUPO,
    ELIMINAR_GRUPO,
    GENERO_ILIMITADO,
    LISTAR_MATCHES,

    // --- AMISTAD CONTROLLER ---
    ENVIAR_SOLICITUD_AMISTAD,
    ACEPTAR_SOLICITUD_AMISTAD,
    RECHAZAR_SOLICITUD_AMISTAD,
    BLOQUEAR_USUARIO,
    CANCELAR_SOLICITUD,
    VER_SOLICITUD,
    VER_SOLICITUDES,
    VER_AMIGOS,
    ELIMINAR_AMIGO,
    VER_COINCIDENCIAS,// exclusivo para ROLE_PREMIUM


    // --- RESENIA CONTROLLER ---
    CREAR_RESENIA,
    ELIMINAR_RESENIA,
    ELIMINAR_RESENIA_POR_USUARIO_Y_CONTENIDO,
    VER_RESENIAS_POR_USUARIO,
    MODIFICAR_RESENIA


}
